# Generated by Django 4.2.1 on 2023-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_description_post_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Notícia', 'Notícia'), ('Resenha', 'Resenha')], default='Notícia', max_length=20),
        ),
    ]
